### ISSUE TITLE
Honkers Railway Not Updated

### ISSUE THREAD

**Issue by 7331Squall** [an-anime-team/anime-games-launcher#22]
I'm not going to say the actual game name for obvious reasons, and I'm sorry if I'm reporting something already known, but...

The game launches normally, but the first message I get is that it's not the latest version and I should update it. No login window, nothing. All I can do is quit it.

Verifying and reinstalling everything also have not fixed the issue.

I think I saw a similar issue on the Honkers Railway own dedicated launcher, though.

**Comment by retrozinndev** [comment]
Yes, you're right about this happening in Honker Railway Launcher, but the issue is already fixed in the single launcher. The "Anime Game Company" changed their API format, so the launcher developer needed to update it. But he didn't update the universal launcher, since it's not completely ready to use and it's not used by many people. 


### Solution
For the moment, you can just use the Honkers Railway Launcher to play the game while the dev doesn't update the launcher.

I hope this explanation helped you.

**Comment by 7331Squall** [comment]
> Yes, you're right about this happening in Honker Railway Launcher, but the issue is already fixed in the single launcher. The "Anime Game Company" changed their API format, so the launcher developer needed to update it. But he didn't update the universal launcher, since it's not completely ready to use and it's not used by many people.
> ### Solution
> 
> For the moment, you can just use the Honkers Railway Launcher to play the game while the dev doesn't update the launcher.
> 
> I hope this explanation helped you.

Well... You don't really fix an issue on an app by telling people to use another one, do you?

I understand where you're coming from, and for all intents and purposed that is the "correct" way to fix the problem, specially because it clearly states on the project description "not for daily usage", but.... It's still an issue on this app, right?

**Comment by retrozinndev** [comment]
Yes, It's still an issue. But the only solution for now is using the other launcher. I'll try solving the problem, but unfortunately I do not know much on how to code in Rust 😆 . I'll try my best and see what I can do about it! For now, wait until someone sends a pull request or dev update the launcher.
